// Generated by Merlin Design LLM v6.x with GSAP Animations - 120% Feature

// Initialize GSAP
if (typeof gsap !== 'undefined' && typeof ScrollTrigger !== 'undefined') {
  gsap.registerPlugin(ScrollTrigger);
}

// GSAP Animations - Professional scroll-triggered animations
document.addEventListener('DOMContentLoaded', () => {
  // Hero section fade-in
  gsap.fromTo('.hero-section, .hero, section:first-of-type',
    { opacity: 0, y: 30 },
    {
      opacity: 1,
      y: 0,
      duration: 1.2,
      delay: 0.2,
      ease: 'power3.out'
    }
  );

  // Sections animate on scroll
  gsap.utils.toArray('.section, section').forEach((section: Element, index: number) => {
    gsap.fromTo(section,
      { opacity: 0, y: 50 },
      {
        opacity: 1,
        y: 0,
        duration: 0.8,
        ease: 'power2.out',
        scrollTrigger: {
          trigger: section,
          start: 'top 80%',
          toggleActions: 'play none none none',
          once: true
        }
      }
    );
  });

  // Cards and feature cards fade in
  gsap.utils.toArray('.card, .feature-card, .service-card').forEach((card: Element, index: number) => {
    gsap.fromTo(card,
      { opacity: 0, scale: 0.9 },
      {
        opacity: 1,
        scale: 1,
        duration: 0.6,
        delay: index * 0.1,
        ease: 'power2.out',
        scrollTrigger: {
          trigger: card,
          start: 'top 85%',
          toggleActions: 'play none none none',
          once: true
        }
      }
    );
  });

  // Smooth scroll for anchor links (GSAP-powered)
  document.querySelectorAll('a[href^="#"]').forEach(anchor => {
    anchor.addEventListener('click', function (e) {
      e.preventDefault();
      const target = document.querySelector(this.getAttribute('href') || '');
      if (target && typeof gsap !== 'undefined') {
        gsap.to(window, {
          duration: 1,
          scrollTo: { y: target, offsetY: 80 },
          ease: 'power2.inOut'
        });
      } else if (target) {
        target.scrollIntoView({ behavior: 'smooth' });
      }
    });
  });
});

// Smooth scroll fallback (if GSAP not loaded)
document.querySelectorAll('a[href^="#"]').forEach(anchor => {
  anchor.addEventListener('click', function (e) {
    e.preventDefault();
    const target = document.querySelector(this.getAttribute('href') || '');
    if (target && typeof gsap === 'undefined') {
      target.scrollIntoView({ behavior: 'smooth' });
    }
  });
});

// Mobile menu toggle (if needed)
const navToggle = document.querySelector('.nav-toggle');
const navLinks = document.querySelector('.nav-links');

if (navToggle) {
  navToggle.addEventListener('click', () => {
    navLinks.classList.toggle('active');
  });
}

// v6.3: FAQ Accordion Toggle
function toggleFAQ(index) {
  const answer = document.getElementById('faq-answer-' + index);
  if (answer) {
    answer.classList.toggle('active');
    const icon = answer.previousElementSibling?.querySelector('.faq-icon');
    if (icon) {
      icon.textContent = answer.classList.contains('active') ? '−' : '+';
    }
  }
}

// v6.3: Testimonials Carousel (basic auto-scroll)
const carouselTrack = document.querySelector('.testimonials-carousel-track');
if (carouselTrack) {
  let scrollPosition = 0;
  const scrollAmount = 320; // card width + gap
  
  setInterval(() => {
    scrollPosition += scrollAmount;
    if (scrollPosition >= carouselTrack.scrollWidth - carouselTrack.clientWidth) {
      scrollPosition = 0;
    }
    carouselTrack.scrollTo({ left: scrollPosition, behavior: 'smooth' });
  }, 3000);
}

// v6.8: Mobile Navigation Toggle
(function() {
  const navToggle = document.querySelector('.cm-nav-toggle');
  const navMenu = document.querySelector('.cm-nav-menu');
  
  if (navToggle && navMenu) {
    navToggle.addEventListener('click', function() {
      const isExpanded = navToggle.getAttribute('aria-expanded') === 'true';
      navToggle.setAttribute('aria-expanded', !isExpanded);
      navMenu.classList.toggle('cm-nav-menu-open');
      navToggle.classList.toggle('cm-nav-toggle-active');
    });
    
    // Close menu when clicking outside
    document.addEventListener('click', function(event) {
      const isClickInside = navToggle.contains(event.target) || navMenu.contains(event.target);
      if (!isClickInside && navMenu.classList.contains('cm-nav-menu-open')) {
        navToggle.setAttribute('aria-expanded', 'false');
        navMenu.classList.remove('cm-nav-menu-open');
        navToggle.classList.remove('cm-nav-toggle-active');
      }
    });
  }
})();
