/**
 * Comprehensive Integrations Catalog
 * Phase 1.4: Expanded from 4 to 50+ integrations
 * 
 * This file contains all available integrations across all categories
 */

import type { Integration } from './integrationService';
import { PHASE_3_INTEGRATIONS } from './integrationExpansionPhase3';

/**
 * EXPANDED INTEGRATIONS CATALOG - 50+ Integrations
 * 
 * Categories:
 * - Analytics (6)
 * - Marketing (8)
 * - Email (5)
 * - Social (6)
 * - CRM (4)
 * - Automation (4)
 * - E-commerce (3)
 * - Customer Support (4)
 * - Forms (3)
 * - Communication (5)
 * - Other (2)
 */

export const EXPANDED_INTEGRATIONS_CATALOG: Integration[] = [
  // ============================================
  // ANALYTICS (6)
  // ============================================
  {
    id: 'google-analytics',
    name: 'Google Analytics',
    description: 'Track website traffic and user behavior with Google Analytics 4',
    category: 'analytics',
    enabled: false,
    requiresAuth: true,
    config: { measurementId: '' },
  },
  {
    id: 'mixpanel',
    name: 'Mixpanel',
    description: 'Product analytics and user behavior tracking',
    category: 'analytics',
    enabled: false,
    requiresAuth: true,
    config: { projectToken: '' },
  },
  {
    id: 'amplitude',
    name: 'Amplitude',
    description: 'Product analytics platform for digital products',
    category: 'analytics',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '' },
  },
  {
    id: 'segment',
    name: 'Segment',
    description: 'Customer data platform and analytics collection',
    category: 'analytics',
    enabled: false,
    requiresAuth: true,
    config: { writeKey: '' },
  },
  {
    id: 'hotjar',
    name: 'Hotjar',
    description: 'Behavior analytics and user feedback tools',
    category: 'analytics',
    enabled: false,
    requiresAuth: true,
    config: { siteId: '' },
  },
  {
    id: 'fullstory',
    name: 'FullStory',
    description: 'Digital experience analytics and session replay',
    category: 'analytics',
    enabled: false,
    requiresAuth: true,
    config: { orgId: '' },
  },
  {
    id: 'posthog',
    name: 'PostHog',
    description: 'Product analytics, feature flags, and session replay',
    category: 'analytics',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '' },
  },

  // ============================================
  // MARKETING (8)
  // ============================================
  {
    id: 'facebook-pixel',
    name: 'Facebook Pixel',
    description: 'Track conversions and create custom audiences for Facebook ads',
    category: 'marketing',
    enabled: false,
    requiresAuth: true,
    config: { pixelId: '' },
  },
  {
    id: 'klaviyo',
    name: 'Klaviyo',
    description: 'Email and SMS marketing automation platform',
    category: 'marketing',
    enabled: false,
    requiresAuth: true,
    config: { publicApiKey: '' },
  },
  {
    id: 'activecampaign',
    name: 'ActiveCampaign',
    description: 'Marketing automation and email marketing platform',
    category: 'marketing',
    enabled: false,
    requiresAuth: true,
    config: { accountId: '', actid: '' },
  },
  {
    id: 'omnisend',
    name: 'Omnisend',
    description: 'E-commerce marketing automation platform',
    category: 'marketing',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '' },
  },
  {
    id: 'brevo',
    name: 'Brevo (Sendinblue)',
    description: 'Email marketing, SMS, and marketing automation',
    category: 'marketing',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '' },
  },
  {
    id: 'hubspot',
    name: 'HubSpot',
    description: 'Marketing, sales, and customer service platform',
    category: 'marketing',
    enabled: false,
    requiresAuth: true,
    config: { portalId: '' },
  },
  {
    id: 'salesforce',
    name: 'Salesforce Marketing Cloud',
    description: 'Enterprise marketing automation and CRM',
    category: 'marketing',
    enabled: false,
    requiresAuth: true,
    config: { accountId: '' },
  },
  {
    id: 'vercel-analytics',
    name: 'Vercel Analytics',
    description: 'Web analytics and performance monitoring',
    category: 'marketing',
    enabled: false,
    requiresAuth: false,
    config: {},
  },

  // ============================================
  // EMAIL (5)
  // ============================================
  {
    id: 'mailchimp',
    name: 'Mailchimp',
    description: 'Sync newsletter signups and manage email campaigns',
    category: 'email',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '', listId: '' },
  },
  {
    id: 'sendgrid',
    name: 'SendGrid',
    description: 'Transactional and marketing email delivery service',
    category: 'email',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '' },
  },
  {
    id: 'convertkit',
    name: 'ConvertKit',
    description: 'Email marketing for creators and bloggers',
    category: 'email',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '', formId: '' },
  },
  {
    id: 'constant-contact',
    name: 'Constant Contact',
    description: 'Email marketing and social media marketing platform',
    category: 'email',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '' },
  },
  {
    id: 'campaign-monitor',
    name: 'Campaign Monitor',
    description: 'Email marketing and automation platform',
    category: 'email',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '', clientId: '' },
  },

  // ============================================
  // SOCIAL (6)
  // ============================================
  {
    id: 'instagram',
    name: 'Instagram Feed',
    description: 'Display Instagram feed on your website',
    category: 'social',
    enabled: false,
    requiresAuth: true,
    config: { accessToken: '', userId: '' },
  },
  {
    id: 'twitter',
    name: 'Twitter Feed',
    description: 'Embed Twitter feed and tweets',
    category: 'social',
    enabled: false,
    requiresAuth: false,
    config: { username: '' },
  },
  {
    id: 'linkedin',
    name: 'LinkedIn Company Page',
    description: 'Display LinkedIn company updates and feed',
    category: 'social',
    enabled: false,
    requiresAuth: true,
    config: { companyId: '' },
  },
  {
    id: 'tiktok',
    name: 'TikTok Feed',
    description: 'Display TikTok videos and feed',
    category: 'social',
    enabled: false,
    requiresAuth: true,
    config: { username: '' },
  },
  {
    id: 'pinterest',
    name: 'Pinterest Widget',
    description: 'Embed Pinterest boards and pins',
    category: 'social',
    enabled: false,
    requiresAuth: false,
    config: { boardUrl: '' },
  },
  {
    id: 'youtube',
    name: 'YouTube Channel',
    description: 'Embed YouTube videos and playlists',
    category: 'social',
    enabled: false,
    requiresAuth: false,
    config: { channelId: '' },
  },

  // ============================================
  // CRM (4)
  // ============================================
  {
    id: 'hubspot-crm',
    name: 'HubSpot CRM',
    description: 'Customer relationship management and sales pipeline',
    category: 'automation',
    enabled: false,
    requiresAuth: true,
    config: { portalId: '', apiKey: '' },
  },
  {
    id: 'salesforce-crm',
    name: 'Salesforce CRM',
    description: 'Enterprise CRM and sales force automation',
    category: 'automation',
    enabled: false,
    requiresAuth: true,
    config: { instanceUrl: '', accessToken: '' },
  },
  {
    id: 'pipedrive',
    name: 'Pipedrive',
    description: 'Sales CRM and pipeline management',
    category: 'automation',
    enabled: false,
    requiresAuth: true,
    config: { apiToken: '' },
  },
  {
    id: 'zoho-crm',
    name: 'Zoho CRM',
    description: 'Cloud-based CRM and sales management',
    category: 'automation',
    enabled: false,
    requiresAuth: true,
    config: { accessToken: '', clientId: '' },
  },

  // ============================================
  // AUTOMATION (4)
  // ============================================
  {
    id: 'zapier',
    name: 'Zapier',
    description: 'Automate workflows by connecting to 5000+ apps via webhooks',
    category: 'automation',
    enabled: false,
    requiresAuth: false,
    config: { webhookUrl: '' },
  },
  {
    id: 'make',
    name: 'Make (Integromat)',
    description: 'Visual automation platform connecting apps and services',
    category: 'automation',
    enabled: false,
    requiresAuth: false,
    config: { webhookUrl: '' },
  },
  {
    id: 'ifttt',
    name: 'IFTTT',
    description: 'Automation platform connecting apps, devices, and services',
    category: 'automation',
    enabled: false,
    requiresAuth: false,
    config: { webhookUrl: '' },
  },
  {
    id: 'n8n',
    name: 'n8n',
    description: 'Workflow automation platform and API integration',
    category: 'automation',
    enabled: false,
    requiresAuth: false,
    config: { webhookUrl: '' },
  },

  // ============================================
  // E-COMMERCE (3)
  // ============================================
  {
    id: 'shopify',
    name: 'Shopify',
    description: 'E-commerce platform integration for product sync',
    category: 'other',
    enabled: false,
    requiresAuth: true,
    config: { shopDomain: '', accessToken: '' },
  },
  {
    id: 'woocommerce',
    name: 'WooCommerce',
    description: 'WordPress e-commerce platform integration',
    category: 'other',
    enabled: false,
    requiresAuth: true,
    config: { storeUrl: '', consumerKey: '', consumerSecret: '' },
  },
  {
    id: 'bigcommerce',
    name: 'BigCommerce',
    description: 'E-commerce platform for online stores',
    category: 'other',
    enabled: false,
    requiresAuth: true,
    config: { storeHash: '', accessToken: '' },
  },

  // ============================================
  // CUSTOMER SUPPORT (4)
  // ============================================
  {
    id: 'intercom',
    name: 'Intercom',
    description: 'Customer messaging platform and support chat',
    category: 'other',
    enabled: false,
    requiresAuth: true,
    config: { appId: '' },
  },
  {
    id: 'zendesk',
    name: 'Zendesk',
    description: 'Customer service platform and support ticketing',
    category: 'other',
    enabled: false,
    requiresAuth: true,
    config: { accountId: '' },
  },
  {
    id: 'freshdesk',
    name: 'Freshdesk',
    description: 'Customer support software and helpdesk',
    category: 'other',
    enabled: false,
    requiresAuth: true,
    config: { domain: '' },
  },
  {
    id: 'drift',
    name: 'Drift',
    description: 'Conversational marketing and sales platform',
    category: 'other',
    enabled: false,
    requiresAuth: true,
    config: { accountId: '' },
  },
  {
    id: 'crisp',
    name: 'Crisp',
    description: 'Customer messaging platform with live chat',
    category: 'other',
    enabled: false,
    requiresAuth: true,
    config: { websiteId: '' },
  },
  {
    id: 'livechat',
    name: 'LiveChat',
    description: 'Live chat software for customer support',
    category: 'other',
    enabled: false,
    requiresAuth: true,
    config: { licenseNumber: '' },
  },

  // ============================================
  // FORMS (3)
  // ============================================
  {
    id: 'typeform',
    name: 'Typeform',
    description: 'Interactive forms and surveys',
    category: 'other',
    enabled: false,
    requiresAuth: false,
    config: { formId: '' },
  },
  {
    id: 'jotform',
    name: 'JotForm',
    description: 'Online form builder and data collection',
    category: 'other',
    enabled: false,
    requiresAuth: false,
    config: { formId: '' },
  },
  {
    id: 'calendly',
    name: 'Calendly',
    description: 'Online appointment scheduling and booking',
    category: 'other',
    enabled: false,
    requiresAuth: false,
    config: { username: '' },
  },

  // ============================================
  // COMMUNICATION (5)
  // ============================================
  {
    id: 'slack',
    name: 'Slack',
    description: 'Team communication and notifications',
    category: 'automation',
    enabled: false,
    requiresAuth: true,
    config: { webhookUrl: '' },
  },
  {
    id: 'discord',
    name: 'Discord',
    description: 'Community platform integration',
    category: 'social',
    enabled: false,
    requiresAuth: false,
    config: { webhookUrl: '' },
  },
  {
    id: 'telegram',
    name: 'Telegram',
    description: 'Messaging platform integration',
    category: 'automation',
    enabled: false,
    requiresAuth: false,
    config: { botToken: '', chatId: '' },
  },
  {
    id: 'whatsapp-business',
    name: 'WhatsApp Business',
    description: 'WhatsApp Business API integration',
    category: 'automation',
    enabled: false,
    requiresAuth: true,
    config: { phoneNumberId: '', accessToken: '' },
  },
  {
    id: 'twilio',
    name: 'Twilio',
    description: 'Communication platform for SMS and voice',
    category: 'automation',
    enabled: false,
    requiresAuth: true,
    config: { accountSid: '', authToken: '' },
  },

  // ============================================
  // OTHER (2)
  // ============================================
  {
    id: 'cloudflare',
    name: 'Cloudflare',
    description: 'CDN, security, and performance optimization',
    category: 'other',
    enabled: false,
    requiresAuth: false,
    config: {},
  },
  {
    id: 'plausible',
    name: 'Plausible Analytics',
    description: 'Privacy-friendly web analytics',
    category: 'analytics',
    enabled: false,
    requiresAuth: false,
    config: { domain: '' },
  },
  {
    id: 'fathom',
    name: 'Fathom Analytics',
    description: 'Privacy-focused website analytics',
    category: 'analytics',
    enabled: false,
    requiresAuth: false,
    config: { siteId: '' },
  },
  
  // ============================================
  // PHASE 2.5: 50 ADDITIONAL INTEGRATIONS (60 → 110)
  // ============================================
  
  // E-commerce Platforms (10)
  {
    id: 'shopify',
    name: 'Shopify',
    description: 'E-commerce platform integration',
    category: 'ecommerce',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '', shopDomain: '' },
  },
  {
    id: 'woocommerce',
    name: 'WooCommerce',
    description: 'WordPress e-commerce plugin integration',
    category: 'ecommerce',
    enabled: false,
    requiresAuth: true,
    config: { apiUrl: '', consumerKey: '', consumerSecret: '' },
  },
  {
    id: 'bigcommerce',
    name: 'BigCommerce',
    description: 'E-commerce platform for online stores',
    category: 'ecommerce',
    enabled: false,
    requiresAuth: true,
    config: { apiToken: '', storeHash: '' },
  },
  {
    id: 'prestashop',
    name: 'PrestaShop',
    description: 'Open-source e-commerce platform',
    category: 'ecommerce',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '', shopUrl: '' },
  },
  {
    id: 'magento',
    name: 'Magento',
    description: 'E-commerce platform integration',
    category: 'ecommerce',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '', baseUrl: '' },
  },
  {
    id: 'square-online',
    name: 'Square Online',
    description: 'Square e-commerce platform',
    category: 'ecommerce',
    enabled: false,
    requiresAuth: true,
    config: { applicationId: '', accessToken: '' },
  },
  {
    id: 'squarespace-commerce',
    name: 'Squarespace Commerce',
    description: 'Squarespace e-commerce integration',
    category: 'ecommerce',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '' },
  },
  {
    id: 'wix-stores',
    name: 'Wix Stores',
    description: 'Wix e-commerce integration',
    category: 'ecommerce',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '' },
  },
  {
    id: 'etsy',
    name: 'Etsy',
    description: 'Etsy marketplace integration',
    category: 'ecommerce',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '', apiSecret: '' },
  },
  {
    id: 'ecwid',
    name: 'Ecwid',
    description: 'Ecwid shopping cart integration',
    category: 'ecommerce',
    enabled: false,
    requiresAuth: true,
    config: { storeId: '', apiToken: '' },
  },
  
  // Additional Payment Processors (5)
  {
    id: 'square-payments',
    name: 'Square Payments',
    description: 'Square payment processing',
    category: 'ecommerce',
    enabled: false,
    requiresAuth: true,
    config: { applicationId: '', accessToken: '' },
  },
  {
    id: 'adyen',
    name: 'Adyen',
    description: 'Global payment platform',
    category: 'ecommerce',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '', merchantAccount: '' },
  },
  {
    id: 'razorpay',
    name: 'Razorpay',
    description: 'Payment gateway for India',
    category: 'ecommerce',
    enabled: false,
    requiresAuth: true,
    config: { keyId: '', keySecret: '' },
  },
  {
    id: 'payu',
    name: 'PayU',
    description: 'Global payment gateway',
    category: 'ecommerce',
    enabled: false,
    requiresAuth: true,
    config: { merchantId: '', apiKey: '' },
  },
  {
    id: 'klarna',
    name: 'Klarna',
    description: 'Buy now, pay later payment solution',
    category: 'ecommerce',
    enabled: false,
    requiresAuth: true,
    config: { username: '', password: '' },
  },
  
  // CRM Systems (10)
  {
    id: 'pipedrive',
    name: 'Pipedrive',
    description: 'Sales CRM and pipeline management',
    category: 'crm',
    enabled: false,
    requiresAuth: true,
    config: { apiToken: '' },
  },
  {
    id: 'zoho-crm',
    name: 'Zoho CRM',
    description: 'Cloud-based CRM platform',
    category: 'crm',
    enabled: false,
    requiresAuth: true,
    config: { clientId: '', clientSecret: '', refreshToken: '' },
  },
  {
    id: 'freshworks-crm',
    name: 'Freshworks CRM',
    description: 'Sales and marketing automation CRM',
    category: 'crm',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '', domain: '' },
  },
  {
    id: 'insightly',
    name: 'Insightly',
    description: 'CRM and project management platform',
    category: 'crm',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '' },
  },
  {
    id: 'sugar-crm',
    name: 'SugarCRM',
    description: 'Customer relationship management platform',
    category: 'crm',
    enabled: false,
    requiresAuth: true,
    config: { username: '', password: '', instanceUrl: '' },
  },
  {
    id: 'copper',
    name: 'Copper',
    description: 'CRM built for Google Workspace',
    category: 'crm',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '' },
  },
  {
    id: 'salesforce',
    name: 'Salesforce',
    description: 'Cloud-based CRM platform',
    category: 'crm',
    enabled: false,
    requiresAuth: true,
    config: { clientId: '', clientSecret: '', instanceUrl: '' },
  },
  {
    id: 'hubspot-crm',
    name: 'HubSpot CRM',
    description: 'Free CRM platform',
    category: 'crm',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '' },
  },
  {
    id: 'zendesk-sell',
    name: 'Zendesk Sell',
    description: 'Sales CRM platform',
    category: 'crm',
    enabled: false,
    requiresAuth: true,
    config: { apiToken: '', email: '' },
  },
  {
    id: 'activecampaign',
    name: 'ActiveCampaign',
    description: 'Marketing automation and CRM',
    category: 'crm',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '', apiUrl: '' },
  },
  
  // Communication Platforms (5)
  {
    id: 'slack',
    name: 'Slack',
    description: 'Team communication and collaboration',
    category: 'communication',
    enabled: false,
    requiresAuth: true,
    config: { webhookUrl: '' },
  },
  {
    id: 'discord',
    name: 'Discord',
    description: 'Community chat platform',
    category: 'communication',
    enabled: false,
    requiresAuth: true,
    config: { webhookUrl: '' },
  },
  {
    id: 'microsoft-teams',
    name: 'Microsoft Teams',
    description: 'Business communication platform',
    category: 'communication',
    enabled: false,
    requiresAuth: true,
    config: { webhookUrl: '' },
  },
  {
    id: 'mattermost',
    name: 'Mattermost',
    description: 'Open-source team collaboration',
    category: 'communication',
    enabled: false,
    requiresAuth: true,
    config: { apiUrl: '', token: '' },
  },
  {
    id: 'zoom',
    name: 'Zoom',
    description: 'Video conferencing platform',
    category: 'communication',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '', apiSecret: '', accountId: '' },
  },
  
  // Project Management (5)
  {
    id: 'asana',
    name: 'Asana',
    description: 'Project and task management',
    category: 'automation',
    enabled: false,
    requiresAuth: true,
    config: { accessToken: '' },
  },
  {
    id: 'trello',
    name: 'Trello',
    description: 'Visual project management boards',
    category: 'automation',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '', apiToken: '' },
  },
  {
    id: 'monday-com',
    name: 'Monday.com',
    description: 'Work management platform',
    category: 'automation',
    enabled: false,
    requiresAuth: true,
    config: { apiToken: '' },
  },
  {
    id: 'jira',
    name: 'Jira',
    description: 'Project management and issue tracking',
    category: 'automation',
    enabled: false,
    requiresAuth: true,
    config: { apiToken: '', email: '', domain: '' },
  },
  {
    id: 'basecamp',
    name: 'Basecamp',
    description: 'Project management and team communication',
    category: 'automation',
    enabled: false,
    requiresAuth: true,
    config: { accessToken: '', refreshToken: '' },
  },
  
  // Video Platforms (5)
  {
    id: 'vimeo',
    name: 'Vimeo',
    description: 'Video hosting and streaming',
    category: 'media',
    enabled: false,
    requiresAuth: true,
    config: { accessToken: '' },
  },
  {
    id: 'wistia',
    name: 'Wistia',
    description: 'Business video hosting platform',
    category: 'media',
    enabled: false,
    requiresAuth: true,
    config: { apiToken: '' },
  },
  {
    id: 'loom',
    name: 'Loom',
    description: 'Video messaging platform',
    category: 'media',
    enabled: false,
    requiresAuth: true,
    config: { apiToken: '' },
  },
  {
    id: 'dailymotion',
    name: 'Dailymotion',
    description: 'Video sharing platform',
    category: 'media',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '', apiSecret: '' },
  },
  {
    id: 'vimeo-ott',
    name: 'Vimeo OTT',
    description: 'Video streaming and monetization',
    category: 'media',
    enabled: false,
    requiresAuth: true,
    config: { accessToken: '' },
  },
  
  // Development Tools (5)
  {
    id: 'github',
    name: 'GitHub',
    description: 'Code repository and version control',
    category: 'development',
    enabled: false,
    requiresAuth: true,
    config: { accessToken: '' },
  },
  {
    id: 'gitlab',
    name: 'GitLab',
    description: 'DevOps and source code management',
    category: 'development',
    enabled: false,
    requiresAuth: true,
    config: { accessToken: '', projectId: '' },
  },
  {
    id: 'bitbucket',
    name: 'Bitbucket',
    description: 'Git code repository',
    category: 'development',
    enabled: false,
    requiresAuth: true,
    config: { username: '', appPassword: '' },
  },
  {
    id: 'vercel',
    name: 'Vercel',
    description: 'Frontend deployment platform',
    category: 'development',
    enabled: false,
    requiresAuth: true,
    config: { accessToken: '', teamId: '' },
  },
  {
    id: 'netlify',
    name: 'Netlify',
    description: 'Web development and hosting platform',
    category: 'development',
    enabled: false,
    requiresAuth: true,
    config: { accessToken: '' },
  },
  
  // Additional Analytics (5)
  {
    id: 'matomo',
    name: 'Matomo',
    description: 'Open-source web analytics',
    category: 'analytics',
    enabled: false,
    requiresAuth: false,
    config: { siteId: '', trackerUrl: '' },
  },
  {
    id: 'clicky',
    name: 'Clicky',
    description: 'Real-time web analytics',
    category: 'analytics',
    enabled: false,
    requiresAuth: false,
    config: { siteId: '' },
  },
  {
    id: 'statcounter',
    name: 'StatCounter',
    description: 'Web traffic analysis',
    category: 'analytics',
    enabled: false,
    requiresAuth: false,
    config: { projectId: '' },
  },
  {
    id: 'piwik-pro',
    name: 'Piwik PRO',
    description: 'Privacy-focused analytics platform',
    category: 'analytics',
    enabled: false,
    requiresAuth: true,
    config: { apiUrl: '', apiToken: '' },
  },
  {
    id: 'adobe-analytics',
    name: 'Adobe Analytics',
    description: 'Enterprise analytics solution',
    category: 'analytics',
    enabled: false,
    requiresAuth: true,
    config: { reportSuiteId: '', apiKey: '' },
  },
];

// Total: 110 integrations across all categories
// Phase 1.4: 60 integrations
// Phase 2.5: 50 additional integrations

