/**
 * Phase 3.2: Integration Expansion
 * Adding 90 more integrations to reach 200 total
 */

import type { Integration } from './integrationService';

/**
 * Additional 90 integrations for Phase 3.2
 * Expanding from 110 to 200 total
 */
export const PHASE_3_INTEGRATIONS: Integration[] = [
  // ============================================
  // E-COMMERCE PLATFORMS (15 more)
  // ============================================
  {
    id: 'ecwid',
    name: 'Ecwid',
    description: 'E-commerce platform for small businesses',
    category: 'ecommerce',
    enabled: false,
    requiresAuth: true,
    config: { storeId: '' },
  },
  {
    id: 'prestashop',
    name: 'PrestaShop',
    description: 'Open-source e-commerce platform',
    category: 'ecommerce',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '' },
  },
  {
    id: 'magento',
    name: 'Magento',
    description: 'Enterprise e-commerce platform',
    category: 'ecommerce',
    enabled: false,
    requiresAuth: true,
    config: { storeUrl: '' },
  },
  {
    id: 'opencart',
    name: 'OpenCart',
    description: 'Open-source online shopping cart system',
    category: 'ecommerce',
    enabled: false,
    requiresAuth: true,
    config: { storeUrl: '' },
  },
  {
    id: 'squarespace-commerce',
    name: 'Squarespace Commerce',
    description: 'E-commerce solution by Squarespace',
    category: 'ecommerce',
    enabled: false,
    requiresAuth: true,
    config: { siteId: '' },
  },
  {
    id: 'wix-stores',
    name: 'Wix Stores',
    description: 'E-commerce platform by Wix',
    category: 'ecommerce',
    enabled: false,
    requiresAuth: true,
    config: { siteId: '' },
  },
  {
    id: 'volusion',
    name: 'Volusion',
    description: 'Cloud-based e-commerce platform',
    category: 'ecommerce',
    enabled: false,
    requiresAuth: true,
    config: { storeUrl: '' },
  },
  {
    id: '3dcart',
    name: '3dcart',
    description: 'E-commerce shopping cart software',
    category: 'ecommerce',
    enabled: false,
    requiresAuth: true,
    config: { storeUrl: '' },
  },
  {
    id: 'sellfy',
    name: 'Sellfy',
    description: 'Sell digital products and subscriptions',
    category: 'ecommerce',
    enabled: false,
    requiresAuth: true,
    config: { storeId: '' },
  },
  {
    id: 'gumroad',
    name: 'Gumroad',
    description: 'Platform for selling digital products',
    category: 'ecommerce',
    enabled: false,
    requiresAuth: true,
    config: { accessToken: '' },
  },
  {
    id: 'sendowl',
    name: 'SendOwl',
    description: 'Sell digital products online',
    category: 'ecommerce',
    enabled: false,
    requiresAuth: true,
    config: { accountId: '' },
  },
  {
    id: 'selz',
    name: 'Selz',
    description: 'Online store builder for digital products',
    category: 'ecommerce',
    enabled: false,
    requiresAuth: true,
    config: { storeId: '' },
  },
  {
    id: 'podia',
    name: 'Podia',
    description: 'Sell online courses and digital products',
    category: 'ecommerce',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '' },
  },
  {
    id: 'teachable',
    name: 'Teachable',
    description: 'Create and sell online courses',
    category: 'ecommerce',
    enabled: false,
    requiresAuth: true,
    config: { schoolId: '' },
  },
  {
    id: 'thinkific',
    name: 'Thinkific',
    description: 'Online course platform',
    category: 'ecommerce',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '' },
  },

  // ============================================
  // CRM SYSTEMS (15 more)
  // ============================================
  {
    id: 'hubspot-crm',
    name: 'HubSpot CRM',
    description: 'Free CRM platform with sales automation',
    category: 'crm',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '' },
  },
  {
    id: 'activecampaign',
    name: 'ActiveCampaign',
    description: 'Marketing automation and CRM platform',
    category: 'crm',
    enabled: false,
    requiresAuth: true,
    config: { apiUrl: '' },
  },
  {
    id: 'infusionsoft',
    name: 'Infusionsoft',
    description: 'Small business CRM and marketing automation',
    category: 'crm',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '' },
  },
  {
    id: 'insightly',
    name: 'Insightly',
    description: 'CRM for small and medium businesses',
    category: 'crm',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '' },
  },
  {
    id: 'nimble',
    name: 'Nimble',
    description: 'Simple CRM for small businesses',
    category: 'crm',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '' },
  },
  {
    id: 'agile-crm',
    name: 'Agile CRM',
    description: 'All-in-one CRM platform',
    category: 'crm',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '' },
  },
  {
    id: 'copper',
    name: 'Copper',
    description: 'CRM designed for Google Workspace',
    category: 'crm',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '' },
  },
  {
    id: 'pipedrive',
    name: 'Pipedrive',
    description: 'Sales-focused CRM platform',
    category: 'crm',
    enabled: false,
    requiresAuth: true,
    config: { apiToken: '' },
  },
  {
    id: 'capsule-crm',
    name: 'Capsule CRM',
    description: 'Simple CRM for small businesses',
    category: 'crm',
    enabled: false,
    requiresAuth: true,
    config: { apiToken: '' },
  },
  {
    id: 'freshsales',
    name: 'Freshsales',
    description: 'CRM software by Freshworks',
    category: 'crm',
    enabled: false,
    requiresAuth: true,
    config: { domain: '' },
  },
  {
    id: 'method',
    name: 'Method CRM',
    description: 'QuickBooks integrated CRM',
    category: 'crm',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '' },
  },
  {
    id: 'vtiger',
    name: 'vtiger CRM',
    description: 'Open-source CRM platform',
    category: 'crm',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '' },
  },
  {
    id: 'sugar-crm',
    name: 'SugarCRM',
    description: 'Open-source CRM platform',
    category: 'crm',
    enabled: false,
    requiresAuth: true,
    config: { instanceUrl: '' },
  },
  {
    id: 'suite-crm',
    name: 'SuiteCRM',
    description: 'Open-source enterprise CRM',
    category: 'crm',
    enabled: false,
    requiresAuth: true,
    config: { apiUrl: '' },
  },
  {
    id: 'dolibarr',
    name: 'Dolibarr',
    description: 'Open-source ERP and CRM',
    category: 'crm',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '' },
  },

  // ============================================
  // PAYMENT PROCESSORS (10 more)
  // ============================================
  {
    id: 'authorize-net',
    name: 'Authorize.Net',
    description: 'Payment gateway for online transactions',
    category: 'ecommerce',
    enabled: false,
    requiresAuth: true,
    config: { apiLoginId: '' },
  },
  {
    id: 'paypal-pro',
    name: 'PayPal Pro',
    description: 'PayPal payment processing for businesses',
    category: 'ecommerce',
    enabled: false,
    requiresAuth: true,
    config: { clientId: '' },
  },
  {
    id: 'braintree',
    name: 'Braintree',
    description: 'PayPal-owned payment gateway',
    category: 'ecommerce',
    enabled: false,
    requiresAuth: true,
    config: { merchantId: '' },
  },
  {
    id: '2checkout',
    name: '2Checkout',
    description: 'Global payment processing platform',
    category: 'ecommerce',
    enabled: false,
    requiresAuth: true,
    config: { merchantCode: '' },
  },
  {
    id: 'payoneer',
    name: 'Payoneer',
    description: 'Global payment platform',
    category: 'ecommerce',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '' },
  },
  {
    id: 'worldpay',
    name: 'Worldpay',
    description: 'Global payment processing',
    category: 'ecommerce',
    enabled: false,
    requiresAuth: true,
    config: { merchantId: '' },
  },
  {
    id: 'payu',
    name: 'PayU',
    description: 'Payment gateway for emerging markets',
    category: 'ecommerce',
    enabled: false,
    requiresAuth: true,
    config: { merchantId: '' },
  },
  {
    id: 'razorpay',
    name: 'Razorpay',
    description: 'Payment gateway for India',
    category: 'ecommerce',
    enabled: false,
    requiresAuth: true,
    config: { keyId: '' },
  },
  {
    id: 'paystack',
    name: 'Paystack',
    description: 'Payment gateway for Africa',
    category: 'ecommerce',
    enabled: false,
    requiresAuth: true,
    config: { publicKey: '' },
  },
  {
    id: 'mollie',
    name: 'Mollie',
    description: 'European payment service provider',
    category: 'ecommerce',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '' },
  },

  // ============================================
  // MARKETING PLATFORMS (10 more)
  // ============================================
  {
    id: 'constant-contact',
    name: 'Constant Contact',
    description: 'Email marketing and automation',
    category: 'marketing',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '' },
  },
  {
    id: 'aweber',
    name: 'AWeber',
    description: 'Email marketing platform',
    category: 'marketing',
    enabled: false,
    requiresAuth: true,
    config: { accessToken: '' },
  },
  {
    id: 'getresponse',
    name: 'GetResponse',
    description: 'Email marketing and automation',
    category: 'marketing',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '' },
  },
  {
    id: 'sendinblue',
    name: 'Sendinblue',
    description: 'Email marketing and SMS platform',
    category: 'marketing',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '' },
  },
  {
    id: 'campaign-monitor',
    name: 'Campaign Monitor',
    description: 'Email marketing platform',
    category: 'marketing',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '' },
  },
  {
    id: 'omnisend',
    name: 'Omnisend',
    description: 'E-commerce marketing automation',
    category: 'marketing',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '' },
  },
  {
    id: 'klaviyo',
    name: 'Klaviyo',
    description: 'E-commerce marketing automation',
    category: 'marketing',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '' },
  },
  {
    id: 'privy',
    name: 'Privy',
    description: 'Conversion and email marketing',
    category: 'marketing',
    enabled: false,
    requiresAuth: true,
    config: { appId: '' },
  },
  {
    id: 'pushcrew',
    name: 'PushCrew',
    description: 'Web push notifications',
    category: 'marketing',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '' },
  },
  {
    id: 'onesignal',
    name: 'OneSignal',
    description: 'Push notification service',
    category: 'marketing',
    enabled: false,
    requiresAuth: true,
    config: { appId: '' },
  },

  // ============================================
  // COMMUNICATION TOOLS (10 more)
  // ============================================
  {
    id: 'twilio',
    name: 'Twilio',
    description: 'Cloud communications platform',
    category: 'communication',
    enabled: false,
    requiresAuth: true,
    config: { accountSid: '' },
  },
  {
    id: 'sendgrid',
    name: 'SendGrid',
    description: 'Email delivery service',
    category: 'communication',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '' },
  },
  {
    id: 'mailgun',
    name: 'Mailgun',
    description: 'Email API service',
    category: 'communication',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '' },
  },
  {
    id: 'postmark',
    name: 'Postmark',
    description: 'Transactional email service',
    category: 'communication',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '' },
  },
  {
    id: 'mandrill',
    name: 'Mandrill',
    description: 'Transactional email by Mailchimp',
    category: 'communication',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '' },
  },
  {
    id: 'pusher',
    name: 'Pusher',
    description: 'Real-time messaging service',
    category: 'communication',
    enabled: false,
    requiresAuth: true,
    config: { appId: '' },
  },
  {
    id: 'pubnub',
    name: 'PubNub',
    description: 'Real-time messaging and notifications',
    category: 'communication',
    enabled: false,
    requiresAuth: true,
    config: { publishKey: '' },
  },
  {
    id: 'socket-io',
    name: 'Socket.IO',
    description: 'Real-time bidirectional communication',
    category: 'communication',
    enabled: false,
    requiresAuth: false,
    config: { serverUrl: '' },
  },
  {
    id: 'vonage',
    name: 'Vonage',
    description: 'Cloud communications API',
    category: 'communication',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '' },
  },
  {
    id: 'messagebird',
    name: 'MessageBird',
    description: 'Cloud communications platform',
    category: 'communication',
    enabled: false,
    requiresAuth: true,
    config: { accessKey: '' },
  },

  // ============================================
  // DEVELOPMENT/DEVOPS (10 more)
  // ============================================
  {
    id: 'jenkins',
    name: 'Jenkins',
    description: 'Open-source automation server',
    category: 'development',
    enabled: false,
    requiresAuth: true,
    config: { serverUrl: '' },
  },
  {
    id: 'circleci',
    name: 'CircleCI',
    description: 'Continuous integration platform',
    category: 'development',
    enabled: false,
    requiresAuth: true,
    config: { apiToken: '' },
  },
  {
    id: 'travis-ci',
    name: 'Travis CI',
    description: 'Continuous integration service',
    category: 'development',
    enabled: false,
    requiresAuth: true,
    config: { apiToken: '' },
  },
  {
    id: 'bitbucket',
    name: 'Bitbucket',
    description: 'Git repository hosting',
    category: 'development',
    enabled: false,
    requiresAuth: true,
    config: { workspace: '' },
  },
  {
    id: 'gitlab',
    name: 'GitLab',
    description: 'DevOps platform',
    category: 'development',
    enabled: false,
    requiresAuth: true,
    config: { projectId: '' },
  },
  {
    id: 'azure-devops',
    name: 'Azure DevOps',
    description: 'Microsoft DevOps platform',
    category: 'development',
    enabled: false,
    requiresAuth: true,
    config: { organization: '' },
  },
  {
    id: 'jira',
    name: 'Jira',
    description: 'Project management and issue tracking',
    category: 'development',
    enabled: false,
    requiresAuth: true,
    config: { siteUrl: '' },
  },
  {
    id: 'linear',
    name: 'Linear',
    description: 'Issue tracking and project management',
    category: 'development',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '' },
  },
  {
    id: 'clickup',
    name: 'ClickUp',
    description: 'Productivity and project management',
    category: 'development',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '' },
  },
  {
    id: 'notion',
    name: 'Notion',
    description: 'All-in-one workspace',
    category: 'development',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '' },
  },

  // ============================================
  // ANALYTICS/DATA (10 more)
  // ============================================
  {
    id: 'segment',
    name: 'Segment',
    description: 'Customer data platform',
    category: 'analytics',
    enabled: false,
    requiresAuth: true,
    config: { writeKey: '' },
  },
  {
    id: 'heap',
    name: 'Heap',
    description: 'Automatic event tracking',
    category: 'analytics',
    enabled: false,
    requiresAuth: true,
    config: { appId: '' },
  },
  {
    id: 'hotjar',
    name: 'Hotjar',
    description: 'Behavior analytics and user feedback',
    category: 'analytics',
    enabled: false,
    requiresAuth: true,
    config: { siteId: '' },
  },
  {
    id: 'fullstory',
    name: 'FullStory',
    description: 'Digital experience analytics',
    category: 'analytics',
    enabled: false,
    requiresAuth: true,
    config: { orgId: '' },
  },
  {
    id: 'logrocket',
    name: 'LogRocket',
    description: 'Session replay and analytics',
    category: 'analytics',
    enabled: false,
    requiresAuth: true,
    config: { appId: '' },
  },
  {
    id: 'mixpanel',
    name: 'Mixpanel',
    description: 'Product analytics platform',
    category: 'analytics',
    enabled: false,
    requiresAuth: true,
    config: { projectToken: '' },
  },
  {
    id: 'kissmetrics',
    name: 'Kissmetrics',
    description: 'Customer engagement automation',
    category: 'analytics',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '' },
  },
  {
    id: 'matomo',
    name: 'Matomo',
    description: 'Open-source web analytics',
    category: 'analytics',
    enabled: false,
    requiresAuth: true,
    config: { siteId: '' },
  },
  {
    id: 'plausible',
    name: 'Plausible Analytics',
    description: 'Privacy-friendly analytics',
    category: 'analytics',
    enabled: false,
    requiresAuth: true,
    config: { siteId: '' },
  },
  {
    id: 'fathom',
    name: 'Fathom Analytics',
    description: 'Privacy-focused analytics',
    category: 'analytics',
    enabled: false,
    requiresAuth: true,
    config: { siteId: '' },
  },

  // ============================================
  // MEDIA/VIDEO (10 more)
  // ============================================
  {
    id: 'vimeo',
    name: 'Vimeo',
    description: 'Video hosting and sharing platform',
    category: 'media',
    enabled: false,
    requiresAuth: true,
    config: { accessToken: '' },
  },
  {
    id: 'wistia',
    name: 'Wistia',
    description: 'Video hosting for business',
    category: 'media',
    enabled: false,
    requiresAuth: true,
    config: { apiToken: '' },
  },
  {
    id: 'brightcove',
    name: 'Brightcove',
    description: 'Video cloud platform',
    category: 'media',
    enabled: false,
    requiresAuth: true,
    config: { accountId: '' },
  },
  {
    id: 'cloudinary',
    name: 'Cloudinary',
    description: 'Image and video management',
    category: 'media',
    enabled: false,
    requiresAuth: true,
    config: { cloudName: '' },
  },
  {
    id: 'imgix',
    name: 'Imgix',
    description: 'Real-time image processing',
    category: 'media',
    enabled: false,
    requiresAuth: true,
    config: { sourceName: '' },
  },
  {
    id: 'unsplash',
    name: 'Unsplash',
    description: 'Stock photography API',
    category: 'media',
    enabled: false,
    requiresAuth: true,
    config: { accessKey: '' },
  },
  {
    id: 'pexels',
    name: 'Pexels',
    description: 'Free stock photos and videos',
    category: 'media',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '' },
  },
  {
    id: 'pixabay',
    name: 'Pixabay',
    description: 'Free images and videos',
    category: 'media',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '' },
  },
  {
    id: 'shutterstock',
    name: 'Shutterstock',
    description: 'Stock photography marketplace',
    category: 'media',
    enabled: false,
    requiresAuth: true,
    config: { clientId: '' },
  },
  {
    id: 'getty-images',
    name: 'Getty Images',
    description: 'Stock photography and video',
    category: 'media',
    enabled: false,
    requiresAuth: true,
    config: { apiKey: '' },
  },
];

