import type { ChecklistItem, PackageId } from '@/types/websiteBuilder';

/**
 * Client Checklist Items
 * Maps to discovery questions for auto-fill functionality
 */
export const CLIENT_CHECKLIST_ITEMS: ChecklistItem[] = [
  // Business Essentials
  {
    id: 'has-business-name',
    label: 'I have a business name',
    category: 'business-essentials',
    mapsTo: 'businessName',
    required: true,
    hint: 'Your business name will appear throughout your website',
  },
  {
    id: 'has-business-email',
    label: 'I have a business email address',
    category: 'business-essentials',
    mapsTo: 'businessEmail',
    required: true,
    hint: 'Required for contact page and communication',
  },
  {
    id: 'has-business-phone',
    label: 'I have a business phone number',
    category: 'business-essentials',
    mapsTo: 'businessPhone',
    required: false,
    hint: 'Optional but recommended for local businesses',
  },
  {
    id: 'has-business-address',
    label: 'I have a physical business address',
    category: 'business-essentials',
    mapsTo: 'businessAddress',
    required: false,
    hint: 'Helps with local SEO and Google Maps integration',
  },
  {
    id: 'has-domain',
    label: 'I have a domain name (or need help getting one)',
    category: 'business-essentials',
    mapsTo: ['domainStatus', 'domainName'],
    required: true,
    hint: 'Domain name helps establish your online presence',
  },
  {
    id: 'knows-industry',
    label: 'I know what industry I am in',
    category: 'business-essentials',
    mapsTo: 'industry',
    required: true,
    hint: 'Helps us apply industry-specific best practices',
  },
  {
    id: 'knows-website-type',
    label: 'I know what type of website I need',
    category: 'business-essentials',
    mapsTo: 'businessType',
    required: true,
    hint: 'e.g., Restaurant, E-commerce, Portfolio, Blog',
  },

  // Services/Products
  {
    id: 'has-services-list',
    label: 'I have a list of my main services/products',
    category: 'services-products',
    mapsTo: 'services',
    required: true,
    hint: 'List your main offerings to showcase on your website',
  },
  {
    id: 'can-rank-services',
    label: 'I can rank them by importance',
    category: 'services-products',
    mapsTo: 'services',
    required: false,
    hint: 'Ranking helps prioritize content on your website',
  },
  {
    id: 'has-service-descriptions',
    label: 'I have descriptions for each service',
    category: 'services-products',
    mapsTo: 'services',
    required: false,
    hint: 'Descriptions help visitors understand your offerings',
  },
  {
    id: 'knows-target-audience',
    label: 'I know my target audience',
    category: 'services-products',
    mapsTo: 'targetAudience',
    required: true,
    hint: 'Understanding your audience helps tailor content and design',
  },
  {
    id: 'knows-unique-selling-points',
    label: 'I understand my unique selling points',
    category: 'services-products',
    mapsTo: 'projectOverview',
    required: false,
    hint: 'What makes your business different?',
  },

  // Branding
  {
    id: 'has-brand-colors',
    label: 'I have brand colors (or want help choosing)',
    category: 'branding',
    mapsTo: ['primaryColor', 'accentColor', 'colorSchemePreset'],
    required: false,
    hint: 'Brand colors create visual identity and recognition',
  },
  {
    id: 'has-logo',
    label: 'I have a logo (or need one created)',
    category: 'branding',
    mapsTo: 'logoUrl',
    required: false,
    hint: 'Logo enhances brand recognition and professionalism',
  },
  {
    id: 'knows-brand-style',
    label: 'I know my brand style (modern, classic, etc.)',
    category: 'branding',
    mapsTo: ['designStyle', 'styleAdjectives'],
    required: false,
    hint: 'Style guides design choices and overall aesthetic',
  },
  {
    id: 'has-font-preferences',
    label: 'I have font preferences (or want suggestions)',
    category: 'branding',
    mapsTo: 'fontStyle',
    required: false,
    hint: 'Typography affects readability and brand perception',
  },
  {
    id: 'has-inspiration-images',
    label: 'I have inspiration images/websites',
    category: 'branding',
    mapsTo: ['inspirationalSites', 'colorPreferenceImages'],
    required: false,
    hint: 'Inspiration helps us understand your design preferences',
  },

  // Content
  {
    id: 'has-existing-content',
    label: 'I have existing content I can use',
    category: 'content',
    mapsTo: 'contentMode',
    required: false,
    autoFillValue: 'user_provided',
    hint: 'Existing content can be used or refined for your website',
  },
  {
    id: 'wants-ai-generated-content',
    label: 'I want AI to generate content for me',
    category: 'content',
    mapsTo: 'contentMode',
    required: false,
    autoFillValue: 'ai_generated',
    hint: 'AI can create professional, SEO-optimized content',
  },
  {
    id: 'knows-pages-needed',
    label: 'I know what pages I need (Home, About, Services, etc.)',
    category: 'content',
    mapsTo: 'pages',
    required: true,
    hint: 'Pages structure your website and organize content',
  },
  {
    id: 'knows-primary-cta',
    label: 'I know my primary call-to-action',
    category: 'content',
    mapsTo: 'primaryCTA',
    required: true,
    hint: 'What action do you want visitors to take?',
  },
  {
    id: 'knows-content-tone',
    label: 'I understand my content tone preferences',
    category: 'content',
    mapsTo: 'contentTone',
    required: false,
    hint: 'Tone affects how your brand communicates (Professional, Friendly, etc.)',
  },

  // Features
  {
    id: 'needs-contact-form',
    label: 'I need a contact form',
    category: 'features',
    mapsTo: 'features',
    required: false,
    hint: 'Contact forms allow visitors to reach you easily',
  },
  {
    id: 'needs-booking',
    label: 'I need online booking/reservations',
    category: 'features',
    mapsTo: 'features',
    required: false,
    hint: 'Booking system for appointments, reservations, etc.',
  },
  {
    id: 'needs-ecommerce',
    label: 'I need e-commerce/shopping cart',
    category: 'features',
    mapsTo: ['enableEcommerce', 'features'],
    required: false,
    hint: 'Sell products or services directly from your website',
  },
  {
    id: 'needs-blog',
    label: 'I need a blog',
    category: 'features',
    mapsTo: 'features',
    required: false,
    hint: 'Blog helps with SEO and engages your audience',
  },
  {
    id: 'needs-social-integration',
    label: 'I need social media integration',
    category: 'features',
    mapsTo: ['features', 'socialMedia'],
    required: false,
    hint: 'Link to your social media profiles',
  },
  {
    id: 'needs-google-maps',
    label: 'I need Google Maps integration',
    category: 'features',
    mapsTo: 'features',
    required: false,
    hint: 'Show your location on an interactive map',
  },
  {
    id: 'needs-live-chat',
    label: 'I need live chat',
    category: 'features',
    mapsTo: 'features',
    required: false,
    hint: 'Real-time customer support via chat',
  },
  {
    id: 'needs-newsletter',
    label: 'I need newsletter signup',
    category: 'features',
    mapsTo: 'features',
    required: false,
    hint: 'Collect email addresses for marketing',
  },
  {
    id: 'needs-gallery',
    label: 'I need photo gallery',
    category: 'features',
    mapsTo: 'features',
    required: false,
    hint: 'Showcase your work, products, or services',
  },
  {
    id: 'needs-video',
    label: 'I need video integration',
    category: 'features',
    mapsTo: 'features',
    required: false,
    hint: 'Embed videos from YouTube, Vimeo, etc.',
  },

  // SEO & Marketing
  {
    id: 'wants-seo-optimization',
    label: 'I want my website optimized for search engines',
    category: 'seo-marketing',
    mapsTo: 'seoKeywords',
    required: false,
    hint: 'SEO helps your website rank higher in search results',
  },
  {
    id: 'knows-target-keywords',
    label: 'I know my target keywords',
    category: 'seo-marketing',
    mapsTo: 'seoKeywords',
    required: false,
    hint: 'Keywords help optimize content for search',
  },
  {
    id: 'has-competitor-websites',
    label: 'I have competitor websites to analyze',
    category: 'seo-marketing',
    mapsTo: 'competitors',
    required: false,
    hint: 'Competitor analysis helps identify opportunities',
  },
  {
    id: 'wants-local-seo',
    label: 'I want local SEO optimization',
    category: 'seo-marketing',
    mapsTo: 'region',
    required: false,
    hint: 'Local SEO helps customers in your area find you',
  },
  {
    id: 'needs-google-business',
    label: 'I need Google Business integration',
    category: 'seo-marketing',
    mapsTo: 'businessAddress',
    required: false,
    hint: 'Google Business listing improves local visibility',
  },
  {
    id: 'wants-analytics',
    label: 'I want analytics tracking',
    category: 'seo-marketing',
    mapsTo: 'features',
    required: false,
    hint: 'Track visitor behavior and website performance',
  },

  // Visual Assets
  {
    id: 'has-business-photos',
    label: 'I have business photos to upload',
    category: 'visual-assets',
    mapsTo: 'businessPhotos',
    required: false,
    hint: 'Photos showcase your business, products, or services',
  },
  {
    id: 'has-product-images',
    label: 'I have product/service images',
    category: 'visual-assets',
    mapsTo: 'businessPhotos',
    required: false,
    hint: 'High-quality images attract and engage visitors',
  },
  {
    id: 'has-team-photos',
    label: 'I have team photos',
    category: 'visual-assets',
    mapsTo: 'businessPhotos',
    required: false,
    hint: 'Team photos build trust and connection',
  },
  {
    id: 'has-location-photos',
    label: 'I have location photos',
    category: 'visual-assets',
    mapsTo: 'businessPhotos',
    required: false,
    hint: 'Location photos help visitors find and recognize your business',
  },
  {
    id: 'has-color-inspiration',
    label: 'I have color inspiration images',
    category: 'visual-assets',
    mapsTo: 'colorPreferenceImages',
    required: false,
    hint: 'Images help us extract your preferred color palette',
  },
  {
    id: 'has-inspirational-websites',
    label: 'I have inspirational websites',
    category: 'visual-assets',
    mapsTo: 'inspirationalSites',
    required: false,
    hint: 'Share websites whose design you admire',
  },

  // Location & Social
  {
    id: 'knows-location',
    label: 'I know my business location (country, region)',
    category: 'location-social',
    mapsTo: ['country', 'region'],
    required: true,
    hint: 'Location helps with local SEO and regional customization',
  },
  {
    id: 'has-facebook',
    label: 'I have Facebook page',
    category: 'location-social',
    mapsTo: 'socialMedia',
    required: false,
    hint: 'Link to your Facebook business page',
  },
  {
    id: 'has-instagram',
    label: 'I have Instagram account',
    category: 'location-social',
    mapsTo: 'socialMedia',
    required: false,
    hint: 'Link to your Instagram profile',
  },
  {
    id: 'has-linkedin',
    label: 'I have LinkedIn profile',
    category: 'location-social',
    mapsTo: 'socialMedia',
    required: false,
    hint: 'Link to your LinkedIn company page',
  },
  {
    id: 'has-twitter',
    label: 'I have Twitter/X account',
    category: 'location-social',
    mapsTo: 'socialMedia',
    required: false,
    hint: 'Link to your Twitter/X profile',
  },
  {
    id: 'has-youtube',
    label: 'I have YouTube channel',
    category: 'location-social',
    mapsTo: 'socialMedia',
    required: false,
    hint: 'Link to your YouTube channel',
  },
  {
    id: 'has-other-social',
    label: 'I have other social media accounts',
    category: 'location-social',
    mapsTo: 'socialMedia',
    required: false,
    hint: 'We support multiple social media platforms',
  },

  // Goals & Preferences
  {
    id: 'knows-primary-goal',
    label: 'I know my primary website goal (generate leads, sell products, showcase work)',
    category: 'goals-preferences',
    mapsTo: 'projectOverview',
    required: true,
    hint: 'Understanding goals helps optimize website design and content',
  },
  {
    id: 'knows-success-metrics',
    label: 'I know my success metrics (traffic, conversions, sales)',
    category: 'goals-preferences',
    mapsTo: 'projectOverview',
    required: false,
    hint: 'Metrics help measure website effectiveness',
  },
  {
    id: 'knows-timeline',
    label: 'I understand my timeline',
    category: 'goals-preferences',
    mapsTo: 'timeline',
    required: false,
    hint: 'Timeline helps prioritize features and content',
  },
  {
    id: 'knows-budget',
    label: 'I know my budget range',
    category: 'goals-preferences',
    mapsTo: 'budgetRange',
    required: false,
    hint: 'Budget helps determine scope and features',
  },
  {
    id: 'prefers-mobile-first',
    label: 'I prefer mobile-first or desktop-first',
    category: 'goals-preferences',
    mapsTo: 'mobilePriority',
    required: false,
    hint: 'Mobile-first prioritizes mobile experience',
  },
  {
    id: 'prefers-theme',
    label: 'I prefer light or dark theme',
    category: 'goals-preferences',
    mapsTo: 'themeMode',
    required: false,
    hint: 'Theme preference affects overall design aesthetic',
  },
];

/**
 * Category Labels
 */
export const CHECKLIST_CATEGORY_LABELS: Record<ChecklistCategory, string> = {
  'business-essentials': 'Business Essentials',
  'services-products': 'Services & Products',
  branding: 'Branding',
  content: 'Content',
  features: 'Features',
  'seo-marketing': 'SEO & Marketing',
  'visual-assets': 'Visual Assets',
  'location-social': 'Location & Social',
  'goals-preferences': 'Goals & Preferences',
};

/**
 * Category Icons (using lucide-react)
 */
export const CHECKLIST_CATEGORY_ICONS: Record<
  ChecklistCategory,
  'Building2' | 'ShoppingCart' | 'Palette' | 'FileText' | 'Settings' | 'BarChart3' | 'Image' | 'MapPin' | 'Target'
> = {
  'business-essentials': 'Building2',
  'services-products': 'ShoppingCart',
  branding: 'Palette',
  content: 'FileText',
  features: 'Settings',
  'seo-marketing': 'BarChart3',
  'visual-assets': 'Image',
  'location-social': 'MapPin',
  'goals-preferences': 'Target',
};

