/**
 * Phase 2.2: Component Library Expansion
 * Adding 90 more components to reach 200 total
 * This will be merged into componentsLibrary.ts
 */

import {
  Layout, Navigation, Menu, ChevronDown,
  Grid, Columns, Layers, Box, ArrowRight, ArrowDown,
  Search, Calendar, Clock, Upload, Filter, BarChart3, Star, 
  FileText, Type, HelpCircle, MessageCircle, AlertCircle, Bell, 
  Eye, Move, Sliders, Image, Video, Headphones,
  Maximize2, ShoppingCart, Plus, DollarSign, Package,
  Code, Tag,
  CreditCard, Monitor, Palette, Shield, 
  Compass, Globe, MapPin,
  Target, Truck, Zap, Play, List
} from 'lucide-react';

export interface ComponentDefinition {
  id: string;
  name: string;
  icon: React.ReactNode;
  category: 'layout' | 'content' | 'ecommerce' | 'social' | 'forms' | 'media' | 'navigation';
  description: string;
  defaultProps?: Record<string, any>;
}

/**
 * Phase 2.2: 90 Additional Components (110 → 200)
 */

export const PHASE_2_COMPONENT_EXPANSION: ComponentDefinition[] = [
  // ============================================
  // ADVANCED NAVIGATION (10 more)
  // ============================================
  {
    id: 'mega-menu',
    name: 'Mega Menu',
    icon: <Menu className="w-4 h-4" />,
    category: 'navigation',
    description: 'Large dropdown menu with multiple columns',
    defaultProps: { columns: 3 },
  },
  {
    id: 'dropdown-menu',
    name: 'Dropdown Menu',
    icon: <ChevronDown className="w-4 h-4" />,
    category: 'navigation',
    description: 'Dropdown navigation menu',
    defaultProps: {},
  },
  {
    id: 'mobile-drawer',
    name: 'Mobile Drawer',
    icon: <Menu className="w-4 h-4" />,
    category: 'navigation',
    description: 'Slide-out drawer menu for mobile',
    defaultProps: { position: 'left' },
  },
  {
    id: 'navigation-tabs',
    name: 'Navigation Tabs',
    icon: <Layout className="w-4 h-4" />,
    category: 'navigation',
    description: 'Tab-based navigation bar',
    defaultProps: {},
  },
  {
    id: 'sticky-nav',
    name: 'Sticky Navigation',
    icon: <Navigation className="w-4 h-4" />,
    category: 'navigation',
    description: 'Sticky navigation that stays on scroll',
    defaultProps: { offset: 0 },
  },
  {
    id: 'footer-nav',
    name: 'Footer Navigation',
    icon: <Layout className="w-4 h-4" />,
    category: 'navigation',
    description: 'Navigation links in footer',
    defaultProps: { columns: 4 },
  },
  {
    id: 'quick-links',
    name: 'Quick Links',
    icon: <ArrowRight className="w-4 h-4" />,
    category: 'navigation',
    description: 'Quick access navigation links',
    defaultProps: {},
  },
  {
    id: 'site-map',
    name: 'Site Map',
    icon: <MapPin className="w-4 h-4" />,
    category: 'navigation',
    description: 'Complete site navigation map',
    defaultProps: {},
  },
  {
    id: 'jump-to',
    name: 'Jump to Section',
    icon: <ArrowDown className="w-4 h-4" />,
    category: 'navigation',
    description: 'Jump to page sections',
    defaultProps: {},
  },
  {
    id: 'menu-toggle',
    name: 'Menu Toggle',
    icon: <Menu className="w-4 h-4" />,
    category: 'navigation',
    description: 'Toggle button for mobile menu',
    defaultProps: {},
  },

  // ============================================
  // COMPLEX FORMS (15 more)
  // ============================================
  {
    id: 'multi-step-form',
    name: 'Multi-Step Form',
    icon: <FileText className="w-4 h-4" />,
    category: 'forms',
    description: 'Form with multiple steps',
    defaultProps: { steps: 3 },
  },
  {
    id: 'wizard-form',
    name: 'Form Wizard',
    icon: <Layout className="w-4 h-4" />,
    category: 'forms',
    description: 'Wizard-style multi-step form',
    defaultProps: { steps: 4 },
  },
  {
    id: 'file-upload-advanced',
    name: 'Advanced File Upload',
    icon: <Upload className="w-4 h-4" />,
    category: 'forms',
    description: 'Drag-and-drop file upload',
    defaultProps: { multiple: true },
  },
  {
    id: 'date-range-picker',
    name: 'Date Range Picker',
    icon: <Calendar className="w-4 h-4" />,
    category: 'forms',
    description: 'Select date range',
    defaultProps: {},
  },
  {
    id: 'time-range-picker',
    name: 'Time Range Picker',
    icon: <Clock className="w-4 h-4" />,
    category: 'forms',
    description: 'Select time range',
    defaultProps: {},
  },
  {
    id: 'color-picker',
    name: 'Color Picker',
    icon: <Palette className="w-4 h-4" />,
    category: 'forms',
    description: 'Color selection input',
    defaultProps: {},
  },
  {
    id: 'range-slider',
    name: 'Range Slider',
    icon: <Sliders className="w-4 h-4" />,
    category: 'forms',
    description: 'Range value slider',
    defaultProps: { min: 0, max: 100 },
  },
  {
    id: 'autocomplete',
    name: 'Autocomplete Input',
    icon: <Search className="w-4 h-4" />,
    category: 'forms',
    description: 'Input with autocomplete suggestions',
    defaultProps: {},
  },
  {
    id: 'tag-input',
    name: 'Tag Input',
    icon: <Tag className="w-4 h-4" />,
    category: 'forms',
    description: 'Input that creates tags',
    defaultProps: {},
  },
  {
    id: 'rich-text-editor',
    name: 'Rich Text Editor',
    icon: <Type className="w-4 h-4" />,
    category: 'forms',
    description: 'WYSIWYG text editor',
    defaultProps: {},
  },
  {
    id: 'form-validation',
    name: 'Form Validation',
    icon: <AlertCircle className="w-4 h-4" />,
    category: 'forms',
    description: 'Real-time form validation',
    defaultProps: {},
  },
  {
    id: 'conditional-fields',
    name: 'Conditional Fields',
    icon: <Filter className="w-4 h-4" />,
    category: 'forms',
    description: 'Fields that show/hide based on conditions',
    defaultProps: {},
  },
  {
    id: 'form-progress',
    name: 'Form Progress',
    icon: <BarChart3 className="w-4 h-4" />,
    category: 'forms',
    description: 'Progress indicator for multi-step forms',
    defaultProps: {},
  },
  {
    id: 'signature-pad',
    name: 'Signature Pad',
    icon: <Type className="w-4 h-4" />,
    category: 'forms',
    description: 'Digital signature input',
    defaultProps: {},
  },
  {
    id: 'captcha',
    name: 'CAPTCHA',
    icon: <Shield className="w-4 h-4" />,
    category: 'forms',
    description: 'CAPTCHA verification',
    defaultProps: {},
  },

  // ============================================
  // ADVANCED INTERACTIVE (20 more)
  // ============================================
  {
    id: 'advanced-carousel',
    name: 'Advanced Carousel',
    icon: <Image className="w-4 h-4" />,
    category: 'content',
    description: 'Carousel with multiple slides',
    defaultProps: { slidesToShow: 3 },
  },
  {
    id: 'timeline-advanced',
    name: 'Advanced Timeline',
    icon: <Clock className="w-4 h-4" />,
    category: 'content',
    description: 'Detailed timeline component',
    defaultProps: { orientation: 'vertical' },
  },
  {
    id: 'progress-tracker',
    name: 'Progress Tracker',
    icon: <BarChart3 className="w-4 h-4" />,
    category: 'content',
    description: 'Visual progress tracking',
    defaultProps: { steps: 5 },
  },
  {
    id: 'advanced-tooltip',
    name: 'Advanced Tooltip',
    icon: <HelpCircle className="w-4 h-4" />,
    category: 'content',
    description: 'Tooltip with rich content',
    defaultProps: { position: 'top' },
  },
  {
    id: 'advanced-popover',
    name: 'Advanced Popover',
    icon: <MessageCircle className="w-4 h-4" />,
    category: 'content',
    description: 'Popover with interactive content',
    defaultProps: {},
  },
  {
    id: 'drawer',
    name: 'Drawer/Sidebar',
    icon: <Layout className="w-4 h-4" />,
    category: 'content',
    description: 'Slide-out drawer panel',
    defaultProps: { position: 'right' },
  },
  {
    id: 'slide-over',
    name: 'Slide Over',
    icon: <ArrowRight className="w-4 h-4" />,
    category: 'content',
    description: 'Slide-over panel',
    defaultProps: {},
  },
  {
    id: 'context-menu',
    name: 'Context Menu',
    icon: <Menu className="w-4 h-4" />,
    category: 'content',
    description: 'Right-click context menu',
    defaultProps: {},
  },
  {
    id: 'command-palette',
    name: 'Command Palette',
    icon: <Search className="w-4 h-4" />,
    category: 'content',
    description: 'Searchable command menu',
    defaultProps: {},
  },
  {
    id: 'floating-action-button',
    name: 'Floating Action Button',
    icon: <Plus className="w-4 h-4" />,
    category: 'content',
    description: 'FAB button for quick actions',
    defaultProps: { position: 'bottom-right' },
  },
  {
    id: 'notification-center',
    name: 'Notification Center',
    icon: <Bell className="w-4 h-4" />,
    category: 'content',
    description: 'Notification dropdown panel',
    defaultProps: {},
  },
  {
    id: 'tour-guide',
    name: 'Tour Guide',
    icon: <Compass className="w-4 h-4" />,
    category: 'content',
    description: 'Interactive product tour',
    defaultProps: {},
  },
  {
    id: 'hotspot',
    name: 'Hotspot',
    icon: <Target className="w-4 h-4" />,
    category: 'content',
    description: 'Interactive hotspot on image',
    defaultProps: {},
  },
  {
    id: 'lottie-animation',
    name: 'Lottie Animation',
    icon: <Play className="w-4 h-4" />,
    category: 'content',
    description: 'Animated graphics component',
    defaultProps: {},
  },
  {
    id: 'particle-effect',
    name: 'Particle Effect',
    icon: <Zap className="w-4 h-4" />,
    category: 'content',
    description: 'Particle animation background',
    defaultProps: {},
  },
  {
    id: 'morphing-shape',
    name: 'Morphing Shape',
    icon: <Layers className="w-4 h-4" />,
    category: 'content',
    description: 'Animated morphing shapes',
    defaultProps: {},
  },
  {
    id: 'ripple-effect',
    name: 'Ripple Effect',
    icon: <Target className="w-4 h-4" />,
    category: 'content',
    description: 'Material design ripple',
    defaultProps: {},
  },
  {
    id: 'hover-reveal',
    name: 'Hover Reveal',
    icon: <Eye className="w-4 h-4" />,
    category: 'content',
    description: 'Content revealed on hover',
    defaultProps: {},
  },
  {
    id: 'sticky-element',
    name: 'Sticky Element',
    icon: <Navigation className="w-4 h-4" />,
    category: 'content',
    description: 'Element that sticks on scroll',
    defaultProps: {},
  },
  {
    id: 'scroll-spy',
    name: 'Scroll Spy',
    icon: <Eye className="w-4 h-4" />,
    category: 'content',
    description: 'Highlights nav based on scroll',
    defaultProps: {},
  },

  // ============================================
  // ADVANCED MEDIA (10 more)
  // ============================================
  {
    id: 'video-gallery',
    name: 'Video Gallery',
    icon: <Video className="w-4 h-4" />,
    category: 'media',
    description: 'Grid of video thumbnails',
    defaultProps: { columns: 3 },
  },
  {
    id: 'audio-gallery',
    name: 'Audio Gallery',
    icon: <Headphones className="w-4 h-4" />,
    category: 'media',
    description: 'Audio playlist gallery',
    defaultProps: {},
  },
  {
    id: 'media-lightbox',
    name: 'Media Lightbox',
    icon: <Maximize2 className="w-4 h-4" />,
    category: 'media',
    description: 'Lightbox for images and videos',
    defaultProps: {},
  },
  {
    id: 'video-playlist',
    name: 'Video Playlist',
    icon: <Video className="w-4 h-4" />,
    category: 'media',
    description: 'Video playlist player',
    defaultProps: {},
  },
  {
    id: '360-viewer',
    name: '360° Viewer',
    icon: <Globe className="w-4 h-4" />,
    category: 'media',
    description: '360-degree image viewer',
    defaultProps: {},
  },
  {
    id: 'image-zoom',
    name: 'Image Zoom',
    icon: <Maximize2 className="w-4 h-4" />,
    category: 'media',
    description: 'Zoomable image component',
    defaultProps: {},
  },
  {
    id: 'image-annotation',
    name: 'Image Annotation',
    icon: <Type className="w-4 h-4" />,
    category: 'media',
    description: 'Add annotations to images',
    defaultProps: {},
  },
  {
    id: 'video-controls',
    name: 'Advanced Video Controls',
    icon: <Video className="w-4 h-4" />,
    category: 'media',
    description: 'Custom video player controls',
    defaultProps: {},
  },
  {
    id: 'audio-visualizer',
    name: 'Audio Visualizer',
    icon: <BarChart3 className="w-4 h-4" />,
    category: 'media',
    description: 'Audio waveform visualizer',
    defaultProps: {},
  },
  {
    id: 'media-carousel',
    name: 'Media Carousel',
    icon: <Image className="w-4 h-4" />,
    category: 'media',
    description: 'Carousel for mixed media',
    defaultProps: {},
  },

  // ============================================
  // ADVANCED LAYOUT (15 more)
  // ============================================
  {
    id: 'split-screen',
    name: 'Split Screen',
    icon: <Columns className="w-4 h-4" />,
    category: 'layout',
    description: 'Two-panel split layout',
    defaultProps: { split: 50 },
  },
  {
    id: 'dashboard-layout',
    name: 'Dashboard Layout',
    icon: <Layout className="w-4 h-4" />,
    category: 'layout',
    description: 'Dashboard-style layout',
    defaultProps: {},
  },
  {
    id: 'card-deck',
    name: 'Card Deck',
    icon: <Grid className="w-4 h-4" />,
    category: 'layout',
    description: 'Deck of cards layout',
    defaultProps: {},
  },
  {
    id: 'waterfall',
    name: 'Waterfall Layout',
    icon: <Layers className="w-4 h-4" />,
    category: 'layout',
    description: 'Waterfall/pinterest layout',
    defaultProps: { columns: 3 },
  },
  {
    id: 'flex-grid',
    name: 'Flex Grid',
    icon: <Grid className="w-4 h-4" />,
    category: 'layout',
    description: 'Flexbox-based grid',
    defaultProps: { columns: 3 },
  },
  {
    id: 'overlay-layout',
    name: 'Overlay Layout',
    icon: <Layers className="w-4 h-4" />,
    category: 'layout',
    description: 'Overlapping content layers',
    defaultProps: {},
  },
  {
    id: 'magazine-layout',
    name: 'Magazine Layout',
    icon: <FileText className="w-4 h-4" />,
    category: 'layout',
    description: 'Magazine-style grid layout',
    defaultProps: {},
  },
  {
    id: 'responsive-breakpoints',
    name: 'Responsive Breakpoints',
    icon: <Monitor className="w-4 h-4" />,
    category: 'layout',
    description: 'Layout with breakpoint controls',
    defaultProps: {},
  },
  {
    id: 'fluid-grid',
    name: 'Fluid Grid',
    icon: <Grid className="w-4 h-4" />,
    category: 'layout',
    description: 'Fluid responsive grid',
    defaultProps: {},
  },
  {
    id: 'aspect-ratio-container',
    name: 'Aspect Ratio Container',
    icon: <Box className="w-4 h-4" />,
    category: 'layout',
    description: 'Container with fixed aspect ratio',
    defaultProps: { ratio: '16:9' },
  },
  {
    id: 'sticky-sidebar',
    name: 'Sticky Sidebar',
    icon: <Layout className="w-4 h-4" />,
    category: 'layout',
    description: 'Sidebar that sticks on scroll',
    defaultProps: {},
  },
  {
    id: 'three-column',
    name: 'Three Column Layout',
    icon: <Columns className="w-4 h-4" />,
    category: 'layout',
    description: 'Three-column layout',
    defaultProps: {},
  },
  {
    id: 'asymmetric-grid',
    name: 'Asymmetric Grid',
    icon: <Grid className="w-4 h-4" />,
    category: 'layout',
    description: 'Asymmetric grid layout',
    defaultProps: {},
  },
  {
    id: 'z-index-stack',
    name: 'Z-Index Stack',
    icon: <Layers className="w-4 h-4" />,
    category: 'layout',
    description: 'Layered z-index stack',
    defaultProps: {},
  },
  {
    id: 'transform-layout',
    name: 'Transform Layout',
    icon: <Move className="w-4 h-4" />,
    category: 'layout',
    description: 'CSS transform-based layout',
    defaultProps: {},
  },

  // ============================================
  // ADVANCED E-COMMERCE (10 more)
  // ============================================
  {
    id: 'product-quick-view',
    name: 'Product Quick View',
    icon: <Eye className="w-4 h-4" />,
    category: 'ecommerce',
    description: 'Quick view product modal',
    defaultProps: {},
  },
  {
    id: 'checkout-flow',
    name: 'Checkout Flow',
    icon: <ShoppingCart className="w-4 h-4" />,
    category: 'ecommerce',
    description: 'Multi-step checkout process',
    defaultProps: { steps: 3 },
  },
  {
    id: 'order-tracking',
    name: 'Order Tracking',
    icon: <Package className="w-4 h-4" />,
    category: 'ecommerce',
    description: 'Order status tracker',
    defaultProps: {},
  },
  {
    id: 'price-comparison',
    name: 'Price Comparison',
    icon: <DollarSign className="w-4 h-4" />,
    category: 'ecommerce',
    description: 'Compare product prices',
    defaultProps: {},
  },
  {
    id: 'product-bundle',
    name: 'Product Bundle',
    icon: <Package className="w-4 h-4" />,
    category: 'ecommerce',
    description: 'Bundle multiple products',
    defaultProps: {},
  },
  {
    id: 'shipping-calculator',
    name: 'Shipping Calculator',
    icon: <Truck className="w-4 h-4" />,
    category: 'ecommerce',
    description: 'Calculate shipping costs',
    defaultProps: {},
  },
  {
    id: 'size-guide',
    name: 'Size Guide',
    icon: <Grid className="w-4 h-4" />,
    category: 'ecommerce',
    description: 'Product size guide',
    defaultProps: {},
  },
  {
    id: 'product-compare',
    name: 'Product Comparison',
    icon: <Grid className="w-4 h-4" />,
    category: 'ecommerce',
    description: 'Compare multiple products',
    defaultProps: { maxProducts: 4 },
  },
  {
    id: 'stock-notifier',
    name: 'Stock Notifier',
    icon: <Bell className="w-4 h-4" />,
    category: 'ecommerce',
    description: 'Notify when back in stock',
    defaultProps: {},
  },
  {
    id: 'gift-card',
    name: 'Gift Card',
    icon: <CreditCard className="w-4 h-4" />,
    category: 'ecommerce',
    description: 'Gift card component',
    defaultProps: {},
  },

  // ============================================
  // ADVANCED CONTENT (10 more)
  // ============================================
  {
    id: 'testimonials-advanced',
    name: 'Advanced Testimonials',
    icon: <Star className="w-4 h-4" />,
    category: 'content',
    description: 'Rich testimonials with photos',
    defaultProps: { showImages: true },
  },
  {
    id: 'pricing-advanced',
    name: 'Advanced Pricing',
    icon: <DollarSign className="w-4 h-4" />,
    category: 'content',
    description: 'Feature-rich pricing tables',
    defaultProps: { plans: 3 },
  },
  {
    id: 'faq-advanced',
    name: 'Advanced FAQ',
    icon: <HelpCircle className="w-4 h-4" />,
    category: 'content',
    description: 'Searchable FAQ section',
    defaultProps: {},
  },
  {
    id: 'blog-layout',
    name: 'Blog Layout',
    icon: <FileText className="w-4 h-4" />,
    category: 'content',
    description: 'Blog post layout',
    defaultProps: {},
  },
  {
    id: 'article-header',
    name: 'Article Header',
    icon: <FileText className="w-4 h-4" />,
    category: 'content',
    description: 'Article header with meta',
    defaultProps: {},
  },
  {
    id: 'reading-progress',
    name: 'Reading Progress',
    icon: <BarChart3 className="w-4 h-4" />,
    category: 'content',
    description: 'Article reading progress bar',
    defaultProps: {},
  },
  {
    id: 'table-of-contents',
    name: 'Table of Contents',
    icon: <List className="w-4 h-4" />,
    category: 'content',
    description: 'Auto-generated TOC',
    defaultProps: {},
  },
  {
    id: 'code-snippet',
    name: 'Code Snippet',
    icon: <Code className="w-4 h-4" />,
    category: 'content',
    description: 'Syntax highlighted code',
    defaultProps: { language: 'javascript' },
  },
  {
    id: 'callout',
    name: 'Callout Box',
    icon: <AlertCircle className="w-4 h-4" />,
    category: 'content',
    description: 'Highlighted callout box',
    defaultProps: { variant: 'info' },
  },
  {
    id: 'accordion-advanced',
    name: 'Advanced Accordion',
    icon: <ChevronDown className="w-4 h-4" />,
    category: 'content',
    description: 'Accordion with icons and nesting',
    defaultProps: {},
  },
];

