/**
 * Natural Language Scraper Service
 * 
 * Allows users to describe what they want in plain English.
 * GPT parses intent and generates scraper config automatically.
 * 
 * Example: "Get me all product names and prices from this page"
 */

import OpenAI from 'openai';
import { getErrorMessage, logError } from '../utils/errorHandler';
import { extractWithVision, type ExtractedData } from './aiVisionScraper';

// Initialize OpenAI client
const openaiKey = process.env.AI_INTEGRATIONS_OPENAI_API_KEY || process.env.OPENAI_API_KEY;
const openai = openaiKey
  ? new OpenAI({
      apiKey: openaiKey,
      baseURL: process.env.AI_INTEGRATIONS_OPENAI_BASE_URL,
    })
  : null;

export interface NaturalLanguageRequest {
  url: string;
  userPrompt: string; // e.g., "Get me all product names and prices"
  useVision?: boolean; // Use AI Vision if true, otherwise generate CSS selectors
}

export interface ScraperConfig {
  method: 'vision' | 'css-selectors' | 'hybrid';
  selectors?: Record<string, string>; // Field name -> CSS selector
  extractionPrompt?: string; // For vision method
  fields: string[]; // List of fields to extract
  confidence: number;
}

/**
 * Parse natural language intent into scraper configuration
 */
export async function parseNaturalLanguageIntent(
  request: NaturalLanguageRequest
): Promise<ScraperConfig> {
  if (!openai) {
    throw new Error('OpenAI API key not configured. Natural Language Scraper requires OPENAI_API_KEY.');
  }

  try {
    console.log(`[Natural Language Scraper] Parsing intent: "${request.userPrompt}"`);

    const systemPrompt = `You are an expert web scraping assistant. Analyze user requests and determine the best extraction method.

Available methods:
1. vision - Use GPT-4 Vision to see the page (best for complex layouts, no selectors needed)
2. css-selectors - Generate CSS selectors for precise extraction (faster, requires selectors)
3. hybrid - Use both methods for maximum accuracy

Return ONLY valid JSON with this structure:
{
  "method": "vision" | "css-selectors" | "hybrid",
  "selectors": {
    "fieldName": "css.selector.here"
  },
  "extractionPrompt": "Detailed prompt for vision extraction",
  "fields": ["field1", "field2", ...],
  "confidence": 0.95
}`;

    const userPrompt = `User wants to scrape: ${request.url}
User's request: "${request.userPrompt}"

Analyze the request and determine:
1. What data fields need to be extracted?
2. What's the best extraction method?
3. If using CSS selectors, what selectors would work?
4. If using vision, what detailed prompt should be used?

Consider:
- If user mentions "all products", "all prices", "everything" -> use vision
- If user mentions specific elements like "the title", "the price" -> CSS selectors might work
- Complex layouts, dynamic content -> vision is better
- Simple, structured pages -> CSS selectors are faster`;

    const response = await openai.chat.completions.create({
      model: 'gpt-4o',
      messages: [
        {
          role: 'system',
          content: systemPrompt,
        },
        {
          role: 'user',
          content: userPrompt,
        },
      ],
      max_tokens: 1500,
      temperature: 0.2,
    });

    const content = response.choices[0]?.message?.content || '{}';
    console.log(`[Natural Language Scraper] Parsed config: ${content.substring(0, 200)}...`);

    // Parse JSON response
    let parsed: ScraperConfig;
    try {
      const jsonMatch = content.match(/```(?:json)?\s*(\{[\s\S]*\})\s*```/);
      const jsonString = jsonMatch ? jsonMatch[1] : content;
      parsed = JSON.parse(jsonString);
    } catch (parseError) {
      const jsonMatch = content.match(/\{[\s\S]*\}/);
      if (jsonMatch) {
        parsed = JSON.parse(jsonMatch[0]);
      } else {
        throw new Error(`Failed to parse AI response as JSON: ${content}`);
      }
    }

    // Validate config
    if (!parsed.method || !parsed.fields || parsed.fields.length === 0) {
      throw new Error('Invalid scraper config generated by AI');
    }

    return parsed;
  } catch (error) {
    logError(error, 'Natural Language Scraper');
    throw new Error(`Natural language parsing failed: ${getErrorMessage(error)}`);
  }
}

/**
 * Execute natural language scraping request
 */
export async function scrapeWithNaturalLanguage(
  request: NaturalLanguageRequest
): Promise<ExtractedData> {
  try {
    // Parse intent
    const config = await parseNaturalLanguageIntent(request);

    // Use vision method if specified or if config recommends it
    if (request.useVision || config.method === 'vision' || config.method === 'hybrid') {
      console.log(`[Natural Language Scraper] Using AI Vision method`);
      return await extractWithVision({
        url: request.url,
        extractionPrompt: config.extractionPrompt || request.userPrompt,
        fullPage: true,
      });
    }

    // Otherwise, use CSS selectors (would need to implement selector-based extraction)
    // For now, fall back to vision
    console.log(`[Natural Language Scraper] Falling back to AI Vision`);
    return await extractWithVision({
      url: request.url,
      extractionPrompt: request.userPrompt,
      fullPage: true,
    });
  } catch (error) {
    logError(error, 'Natural Language Scraper');
    throw error;
  }
}

/**
 * Common natural language patterns and their extraction methods
 */
export const COMMON_PATTERNS: Record<string, { method: ScraperConfig['method']; prompt: string }> = {
  'product': {
    method: 'vision',
    prompt: 'Extract all product names, prices, images, and descriptions',
  },
  'price': {
    method: 'vision',
    prompt: 'Extract all prices and associated product/service names',
  },
  'contact': {
    method: 'vision',
    prompt: 'Extract all contact information: emails, phones, addresses, social links',
  },
  'email': {
    method: 'css-selectors',
    prompt: 'Extract all email addresses',
  },
  'phone': {
    method: 'css-selectors',
    prompt: 'Extract all phone numbers',
  },
  'title': {
    method: 'css-selectors',
    prompt: 'Extract the page title and main heading',
  },
  'links': {
    method: 'css-selectors',
    prompt: 'Extract all links and their text',
  },
};

