// Generated by Merlin Design LLM v6.3 - Component Variants

// Smooth scroll
document.querySelectorAll('a[href^="#"]').forEach(anchor => {
  anchor.addEventListener('click', function (e) {
    e.preventDefault();
    const target = document.querySelector(this.getAttribute('href'));
    if (target) {
      target.scrollIntoView({ behavior: 'smooth' });
    }
  });
});

// Mobile menu toggle (if needed)
const navToggle = document.querySelector('.nav-toggle');
const navLinks = document.querySelector('.nav-links');

if (navToggle) {
  navToggle.addEventListener('click', () => {
    navLinks.classList.toggle('active');
  });
}

// v6.3: FAQ Accordion Toggle
function toggleFAQ(index) {
  const answer = document.getElementById('faq-answer-' + index);
  if (answer) {
    answer.classList.toggle('active');
    const icon = answer.previousElementSibling?.querySelector('.faq-icon');
    if (icon) {
      icon.textContent = answer.classList.contains('active') ? '−' : '+';
    }
  }
}

// v6.3: Testimonials Carousel (basic auto-scroll)
const carouselTrack = document.querySelector('.testimonials-carousel-track');
if (carouselTrack) {
  let scrollPosition = 0;
  const scrollAmount = 320; // card width + gap
  
  setInterval(() => {
    scrollPosition += scrollAmount;
    if (scrollPosition >= carouselTrack.scrollWidth - carouselTrack.clientWidth) {
      scrollPosition = 0;
    }
    carouselTrack.scrollTo({ left: scrollPosition, behavior: 'smooth' });
  }, 3000);
}

// v6.8: Mobile Navigation Toggle
(function() {
  const navToggle = document.querySelector('.cm-nav-toggle');
  const navMenu = document.querySelector('.cm-nav-menu');
  
  if (navToggle && navMenu) {
    navToggle.addEventListener('click', function() {
      const isExpanded = navToggle.getAttribute('aria-expanded') === 'true';
      navToggle.setAttribute('aria-expanded', !isExpanded);
      navMenu.classList.toggle('cm-nav-menu-open');
      navToggle.classList.toggle('cm-nav-toggle-active');
    });
    
    // Close menu when clicking outside
    document.addEventListener('click', function(event) {
      const isClickInside = navToggle.contains(event.target) || navMenu.contains(event.target);
      if (!isClickInside && navMenu.classList.contains('cm-nav-menu-open')) {
        navToggle.setAttribute('aria-expanded', 'false');
        navMenu.classList.remove('cm-nav-menu-open');
        navToggle.classList.remove('cm-nav-toggle-active');
      }
    });
  }
})();
